modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/template-mod/issues"
license = "https://github.com/team-abnormals/template-mod/blob/main/LICENSE.txt"

[[mods]]
    modId = "farmersassortment"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:dirt"
    configBackground = "minecraft:textures/block/dirt.png"
    authors = "Team Dolt and Tio"
    credits = "Dolt and Tio"
    displayURL = ""
    displayName = "Farmer's Assortment"
    description = '''A fresh start for Farmer's Assortment.'''

[[dependencies.farmersassortment]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.farmersassortment]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.farmersassortment]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.farmersassortment]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.2.0,)"
    ordering = "AFTER"
    side = "BOTH"
